[package]
name = "BottlesOfBeer"
version = "0.1.0"
authors = ["lunarised <j@p7.co.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
